copy "%SystemRoot%\cursors\aero_arrow_l.cur" aero_arrow_l.cur
copy "%SystemRoot%\cursors\aero_helpsel_l.cur" aero_helpsel_l.cur
copy "%SystemRoot%\cursors\aero_working_l.ani" aero_working_l.ani
copy "%SystemRoot%\cursors\aero_busy_l.ani" aero_busy_l.ani
copy "%SystemRoot%\cursors\aero_pen_l.cur" aero_pen_l.cur
copy "%SystemRoot%\cursors\aero_unavail_l.cur" aero_unavail_l.cur
copy "%SystemRoot%\cursors\aero_ns_l.cur" aero_ns_l.cur
copy "%SystemRoot%\cursors\aero_ew_l.cur" aero_ew_l.cur
copy "%SystemRoot%\cursors\aero_nwse_l.cur" aero_nwse_l.cur
copy "%SystemRoot%\cursors\aero_nesw_l.cur" aero_nesw_l.cur
copy "%SystemRoot%\cursors\aero_move_l.cur" aero_move_l.cur
copy "%SystemRoot%\cursors\aero_up_l.cur" aero_up_l.cur
copy "%SystemRoot%\cursors\aero_link_l.cur" aero_link_l.cur
