copy "%SystemRoot%\cursors\aero_arrow.cur" aero_arrow.cur
copy "%SystemRoot%\cursors\aero_helpsel.cur" aero_helpsel.cur
copy "%SystemRoot%\cursors\aero_working.ani" aero_working.ani
copy "%SystemRoot%\cursors\aero_busy.ani" aero_busy.ani
copy "%SystemRoot%\cursors\aero_pen.cur" aero_pen.cur
copy "%SystemRoot%\cursors\aero_unavail.cur" aero_unavail.cur
copy "%SystemRoot%\cursors\aero_ns.cur" aero_ns.cur
copy "%SystemRoot%\cursors\aero_ew.cur" aero_ew.cur
copy "%SystemRoot%\cursors\aero_nwse.cur" aero_nwse.cur
copy "%SystemRoot%\cursors\aero_nesw.cur" aero_nesw.cur
copy "%SystemRoot%\cursors\aero_move.cur" aero_move.cur
copy "%SystemRoot%\cursors\aero_up.cur" aero_up.cur
copy "%SystemRoot%\cursors\aero_link.cur" aero_link.cur
